Vagrant::Config.run do |config|
	config.vm.box = "wdk"
	config.vm.boot_mode = "gui"
	config.vm.forward_port("console", 8008, 8008)
	config.vm.forward_port("ssh", 22, 2222)
  config.vm.share_folder("devwidgets", "/devwidgets", ".")
end
